use egui::Color32;

use crate::model::*;

// NOTE: below data generated by ChatGPT, fact-checking follows later

pub const START_YEAR: i32 = 1983;
pub const END_YEAR: i32 = 2026; // the year after the last one shown

pub const LINEAGES: &[Lineage] = &[
    Lineage {
        name: "Nintendo (Home)",
        maker: Maker::Nintendo,
        color: Color32::from_rgb(0xe4, 0, 0xf),
        consoles: &[
            Console {
                name: "Nintendo Entertainment System",
                short_name: "NES",
                generation: Some(3),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 1983, m: 7, d: 15 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 1985, m: 10, d: 18 },
                        source: None,
                    },
                ],
                milestones: &[
                    Milestone {
                        kind: MilestoneKind::EndOfProduction,
                        date: PartialDate::Year { y: 1995 },
                        region: Some(Region::NA),
                        source: None,
                    },
                    Milestone {
                        kind: MilestoneKind::EndOfProduction,
                        date: PartialDate::Year { y: 2003 },
                        region: Some(Region::JP),
                        source: None,
                    },
                ],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 61_910_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2004),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "Super Nintendo Entertainment System",
                short_name: "SNES",
                generation: Some(4),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 1990, m: 11, d: 21 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::Year { y: 1991 },
                        source: None,
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::EndOfProduction,
                    date: PartialDate::Year { y: 2003 },
                    region: Some(Region::JP),
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 49_100_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2003),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "Nintendo 64",
                short_name: "N64",
                generation: Some(5),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 1996, m: 6, d: 23 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 1996, m: 9, d: 29 },
                        source: None,
                    },
                ],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 32_930_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2002),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "Nintendo GameCube",
                short_name: "GCN",
                generation: Some(6),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2001, m: 9, d: 14 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2001, m: 11, d: 18 },
                        source: None,
                    },
                ],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 21_740_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2007),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "Nintendo Wii",
                short_name: "Wii",
                generation: Some(7),
                releases: &[Release {
                    region: Region::NA,
                    date: PartialDate::YearMonthDay { y: 2006, m: 11, d: 19 },
                    source: None,
                }],
                milestones: &[Milestone {
                    kind: MilestoneKind::EndOfProduction,
                    date: PartialDate::Year { y: 2013 },
                    region: None,
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 101_630_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2016),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "Nintendo Wii U",
                short_name: "Wii U",
                generation: Some(8),
                releases: &[Release {
                    region: Region::NA,
                    date: PartialDate::YearMonthDay { y: 2012, m: 11, d: 18 },
                    source: None,
                }],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 13_560_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2017),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "Nintendo Switch",
                short_name: "Switch",
                generation: Some(9),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2017, m: 3, d: 3 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2017, m: 3, d: 3 },
                        source: None,
                    },
                ],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 153_100_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2025),
                    source: None,
                }],
                series: &[],
            },
        ],
    },
    Lineage {
        name: "PlayStation (Home)",
        maker: Maker::Sony,
        color: Color32::from_rgb(0x00, 0x6f, 0xcd),
        consoles: &[
            Console {
                name: "PlayStation",
                short_name: "PS",
                generation: Some(5),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 1994, m: 12, d: 3 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 1995, m: 9, d: 9 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 1995, m: 9, d: 29 },
                        source: None,
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::EndOfProduction,
                    // Global EoP widely cited as 2006-03-23
                    date: PartialDate::YearMonthDay { y: 2006, m: 3, d: 23 },
                    region: Some(Region::Global),
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 102_490_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2003),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 2",
                short_name: "PS2",
                generation: Some(6),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2000, m: 3, d: 4 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2000, m: 10, d: 26 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2000, m: 11, d: 24 },
                        source: None,
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::EndOfProduction,
                    date: PartialDate::YearMonthDay { y: 2013, m: 1, d: 4 },
                    region: Some(Region::JP),
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    // Officially acknowledged at 160.63m in 2024
                    value: Estimate {
                        point: 160_630_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2024),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 3",
                short_name: "PS3",
                generation: Some(7),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2006, m: 11, d: 11 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2006, m: 11, d: 17 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2007, m: 3, d: 23 },
                        source: None,
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::EndOfProduction,
                    date: PartialDate::YearMonthDay { y: 2017, m: 5, d: 29 },
                    region: Some(Region::JP),
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 87_400_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2017),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 4",
                short_name: "PS4",
                generation: Some(8),
                releases: &[
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2013, m: 11, d: 15 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2013, m: 11, d: 29 },
                        source: None,
                    },
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2014, m: 2, d: 22 },
                        source: None,
                    },
                ],
                milestones: &[
                    // Most PS4 models discontinued in JP on 2021-01-05
                    Milestone {
                        kind: MilestoneKind::EndOfProduction,
                        date: PartialDate::YearMonthDay { y: 2021, m: 1, d: 5 },
                        region: Some(Region::JP),
                        source: None,
                    },
                    // Reports indicate full JP discontinuation in 2025-04; keep as regional milestone
                    Milestone {
                        kind: MilestoneKind::EndOfProduction,
                        date: PartialDate::YearMonthDay { y: 2025, m: 4, d: 4 },
                        region: Some(Region::JP),
                        source: None,
                    },
                ],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    // Shipments as of 2022-03-31
                    value: Estimate {
                        point: 117_200_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2022),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 5",
                short_name: "PS5",
                generation: Some(9),
                releases: &[
                    // Launched Nov 12 in NA/JP; Nov 19 in EU
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2020, m: 11, d: 12 },
                        source: None,
                    },
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2020, m: 11, d: 12 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2020, m: 11, d: 19 },
                        source: None,
                    },
                ],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 80_300_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2025),
                    source: None,
                }],
                series: &[],
            },
        ],
    },
];
