use egui::Color32;

use crate::{model::*, source};

// NOTE: most data below generated by ChatGPT. fact-checking is in progress.

pub const START_YEAR: i32 = 1983;
pub const END_YEAR: i32 = 2026; // the year after the last one shown

pub const LINEAGES: &[Lineage] = &[
    Lineage {
        name: "Nintendo (Home)",
        maker: Maker::Nintendo,
        color: Color32::from_rgb(0xe4, 0, 0xf),
        consoles: &[
            Console {
                name: "Nintendo Entertainment System",
                short_name: "NES",
                generation: Some(3),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(1983, 7, 15),
                        source: source!(wikipedia: "NES"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(1985, 10, 18),
                        source: source!(wikipedia: "NES"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(1986, 9, 1),
                        source: source!(wikipedia: "NES"),
                    },
                ],
                milestones: &[
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(1995, 8, 14),
                        region: Region::EU,
                        source: source!(wikipedia: "NES"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(1995, 8, 14),
                        region: Region::NA,
                        source: source!(wikipedia: "NES"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(2003, 9, 25),
                        region: Region::JP,
                        source: source!(wikipedia: "NES"),
                    },
                ],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 61_910_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2016),
                    source: source!(wikipedia: "NES"),
                }],
                series: &[],
            },
            Console {
                name: "Super Nintendo Entertainment System",
                short_name: "SNES",
                generation: Some(4),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(1990, 11, 21),
                        source: source!(wikipedia: "SNES"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(1991, 8, 23),
                        source: source!(wikipedia: "SNES"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ym(1992, 6),
                        source: source!(wikipedia: "SNES"),
                    },
                ],
                milestones: &[
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::y(1998),
                        region: Region::EU,
                        source: source!(wikipedia: "SNES"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(1999, 11, 30),
                        region: Region::NA,
                        source: source!(wikipedia: "SNES"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(2003, 9, 25),
                        region: Region::JP,
                        source: source!(wikipedia: "SNES"),
                    },
                ],
                measures: &[
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 49_100_000,
                            low: None,
                            high: None,
                        },
                        region: Region::Global,
                        as_of_year: Some(2017),
                        source: source!(wikipedia: "SNES"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 23_350_000,
                            low: None,
                            high: None,
                        },
                        region: Region::NA,
                        as_of_year: Some(2017),
                        source: source!(wikipedia: "SNES"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 17_170_000,
                            low: None,
                            high: None,
                        },
                        region: Region::JP,
                        as_of_year: Some(2017),
                        source: source!(wikipedia: "SNES"),
                    },
                ],
                series: &[],
            },
            Console {
                name: "Nintendo 64",
                short_name: "N64",
                generation: Some(5),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(1996, 6, 23),
                        source: source!(wikipedia: "N64"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(1996, 9, 29),
                        source: source!(wikipedia: "N64"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(1997, 3, 1),
                        source: source!(wikipedia: "N64"),
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::ymd(2002, 4, 30),
                    region: Region::Global,
                    source: source!(wikipedia: "N64"),
                }],
                measures: &[
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 32_930_000,
                            low: None,
                            high: None,
                        },
                        region: Region::Global,
                        as_of_year: Some(2010),
                        source: source!(wikipedia: "N64"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 5_540_000,
                            low: None,
                            high: None,
                        },
                        region: Region::JP,
                        as_of_year: Some(2010),
                        source: source!(wikipedia: "N64"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 20_630_000,
                            low: None,
                            high: None,
                        },
                        region: Region::NA,
                        as_of_year: Some(2010),
                        source: source!(wikipedia: "N64"),
                    },
                ],
                series: &[],
            },
            Console {
                name: "Nintendo GameCube",
                short_name: "GCN",
                generation: Some(6),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(2001, 9, 14),
                        source: source!(wikipedia: "GameCube"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(2001, 11, 18),
                        source: source!(wikipedia: "GameCube"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(2002, 5, 3),
                        source: source!(wikipedia: "GameCube"),
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::ym(2007, 8),
                    region: Region::Global,
                    source: source!(wikipedia: "GameCube"),
                }],
                measures: &[
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 21_740_000,
                            low: None,
                            high: None,
                        },
                        region: Region::Global,
                        as_of_year: Some(2011),
                        source: source!(wikipedia: "GameCube"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 12_940_000,
                            low: None,
                            high: None,
                        },
                        region: Region::NA,
                        as_of_year: Some(2011),
                        source: source!(wikipedia: "GameCube"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 4_040_000,
                            low: None,
                            high: None,
                        },
                        region: Region::JP,
                        as_of_year: Some(2011),
                        source: source!(wikipedia: "GameCube"),
                    },
                ],
                series: &[],
            },
            Console {
                name: "Nintendo Wii",
                short_name: "Wii",
                generation: Some(7),
                releases: &[
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(2006, 11, 19),
                        source: source!(wikipedia: "Wii"),
                    },
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(2006, 12, 2),
                        source: source!(wikipedia: "Wii"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(2006, 12, 8),
                        source: source!(wikipedia: "Wii"),
                    },
                ],
                milestones: &[
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(2013, 10, 20),
                        region: Region::JP,
                        source: source!(wikipedia: "Wii"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(2013, 10, 24),
                        region: Region::EU,
                        source: source!(wikipedia: "Wii"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ym(2014, 5),
                        region: Region::NA,
                        source: source!(wikipedia: "Wii"),
                    },
                ],
                measures: &[
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 101_630_000,
                            low: None,
                            high: None,
                        },
                        region: Region::Global,
                        as_of_year: Some(2016),
                        source: source!(wikipedia: "Wii"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 12_750_000,
                            low: None,
                            high: None,
                        },
                        region: Region::JP,
                        as_of_year: Some(2016),
                        source: source!(wikipedia: "Wii"),
                    },
                    Measure {
                        kind: MeasureKind::UnitsSold,
                        value: Estimate {
                            point: 48_640_000,
                            low: None,
                            high: None,
                        },
                        region: Region::NA,
                        as_of_year: Some(2016),
                        source: source!(wikipedia: "Wii"),
                    },
                ],
                series: &[],
            },
            Console {
                name: "Nintendo Wii U",
                short_name: "Wii U",
                generation: Some(8),
                releases: &[
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(2012, 11, 18),
                        source: source!(wikipedia: "Wii U"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(2012, 11, 30),
                        source: source!(wikipedia: "Wii U"),
                    },
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(2012, 12, 8),
                        source: source!(wikipedia: "Wii U"),
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::ymd(2017, 1, 31),
                    region: Region::Global,
                    source: source!(wikipedia: "Wii U"),
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 13_560_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2019),
                    source: source!(wikipedia: "Wii U"),
                }],
                series: &[],
            },
            Console {
                name: "Nintendo Switch",
                short_name: "Switch",
                generation: Some(9),
                releases: &[Release {
                    region: Region::Global,
                    date: PartialDate::ymd(2017, 3, 3),
                    source: source!(wikipedia: "Nintendo_Switch"),
                }],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 153_100_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2025),
                    source: source!(wikipedia: "Nintendo_Switch"),
                }],
                series: &[],
            },
        ],
    },
    Lineage {
        name: "PlayStation (Home)",
        maker: Maker::Sony,
        color: Color32::from_rgb(0x00, 0x6f, 0xcd),
        consoles: &[
            Console {
                name: "PlayStation",
                short_name: "PS",
                generation: Some(5),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 1994, m: 12, d: 3 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 1995, m: 9, d: 9 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 1995, m: 9, d: 29 },
                        source: None,
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    // Global EoP widely cited as 2006-03-23
                    date: PartialDate::YearMonthDay { y: 2006, m: 3, d: 23 },
                    region: Region::Global,
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 102_490_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2003),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 2",
                short_name: "PS2",
                generation: Some(6),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2000, m: 3, d: 4 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2000, m: 10, d: 26 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2000, m: 11, d: 24 },
                        source: None,
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::YearMonthDay { y: 2013, m: 1, d: 4 },
                    region: Region::JP,
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    // Officially acknowledged at 160.63m in 2024
                    value: Estimate {
                        point: 160_630_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2024),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 3",
                short_name: "PS3",
                generation: Some(7),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2006, m: 11, d: 11 },
                        source: None,
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2006, m: 11, d: 17 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2007, m: 3, d: 23 },
                        source: None,
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::YearMonthDay { y: 2017, m: 5, d: 29 },
                    region: Region::JP,
                    source: None,
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 87_400_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2017),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 4",
                short_name: "PS4",
                generation: Some(8),
                releases: &[
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2013, m: 11, d: 15 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2013, m: 11, d: 29 },
                        source: None,
                    },
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2014, m: 2, d: 22 },
                        source: None,
                    },
                ],
                milestones: &[
                    // Most PS4 models discontinued in JP on 2021-01-05
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::YearMonthDay { y: 2021, m: 1, d: 5 },
                        region: Region::JP,
                        source: None,
                    },
                    // Reports indicate full JP discontinuation in 2025-04; keep as regional milestone
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::YearMonthDay { y: 2025, m: 4, d: 4 },
                        region: Region::JP,
                        source: None,
                    },
                ],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    // Shipments as of 2022-03-31
                    value: Estimate {
                        point: 117_200_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2022),
                    source: None,
                }],
                series: &[],
            },
            Console {
                name: "PlayStation 5",
                short_name: "PS5",
                generation: Some(9),
                releases: &[
                    // Launched Nov 12 in NA/JP; Nov 19 in EU
                    Release {
                        region: Region::NA,
                        date: PartialDate::YearMonthDay { y: 2020, m: 11, d: 12 },
                        source: None,
                    },
                    Release {
                        region: Region::JP,
                        date: PartialDate::YearMonthDay { y: 2020, m: 11, d: 12 },
                        source: None,
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::YearMonthDay { y: 2020, m: 11, d: 19 },
                        source: None,
                    },
                ],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 80_300_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2025),
                    source: None,
                }],
                series: &[],
            },
        ],
    },
    Lineage {
        name: "Nintendo (Portable)",
        maker: Maker::Nintendo,
        color: Color32::from_rgb(0x8f, 0x8f, 0x8f), // Gray color for portables
        consoles: &[
            Console {
                name: "Game Boy",
                short_name: "GB",
                generation: Some(4),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(1989, 4, 21),
                        source: source!(wikipedia: "Game_Boy"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(1989, 7, 31),
                        source: source!(wikipedia: "Game_Boy"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(1990, 9, 28),
                        source: source!(wikipedia: "Game_Boy"),
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::ymd(2003, 3, 31),
                    region: Region::Global,
                    source: source!(wikipedia: "Game_Boy"),
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 118_690_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2003),
                    source: source!(wikipedia: "Game_Boy"),
                }],
                series: &[],
            },
            Console {
                name: "Game Boy Color",
                short_name: "GBC",
                generation: Some(5),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(1998, 10, 21),
                        source: source!(wikipedia: "Game_Boy_Color"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(1998, 11, 18),
                        source: source!(wikipedia: "Game_Boy_Color"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(1998, 11, 23),
                        source: source!(wikipedia: "Game_Boy_Color"),
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::ymd(2003, 3, 31),
                    region: Region::Global,
                    source: source!(wikipedia: "Game_Boy_Color"),
                }],
                measures: &[],
                series: &[],
            },
            Console {
                name: "Game Boy Advance",
                short_name: "GBA",
                generation: Some(6),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(2001, 3, 21),
                        source: source!(wikipedia: "Game_Boy_Advance"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(2001, 6, 11),
                        source: source!(wikipedia: "Game_Boy_Advance"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(2001, 6, 22),
                        source: source!(wikipedia: "Game_Boy_Advance"),
                    },
                ],
                milestones: &[
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(2008, 11, 18),
                        region: Region::JP,
                        source: source!(wikipedia: "Game_Boy_Advance"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(2009, 10, 16),
                        region: Region::EU,
                        source: source!(wikipedia: "Game_Boy_Advance"),
                    },
                    Milestone {
                        kind: MilestoneKind::Discontinued,
                        date: PartialDate::ymd(2009, 12, 9),
                        region: Region::NA,
                        source: source!(wikipedia: "Game_Boy_Advance"),
                    },
                ],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 81_510_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2010),
                    source: source!(wikipedia: "Game_Boy_Advance"),
                }],
                series: &[],
            },
            Console {
                name: "Nintendo DS",
                short_name: "DS",
                generation: Some(7),
                releases: &[
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(2004, 11, 21),
                        source: source!(wikipedia: "Nintendo_DS"),
                    },
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(2004, 12, 2),
                        source: source!(wikipedia: "Nintendo_DS"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(2005, 3, 11),
                        source: source!(wikipedia: "Nintendo_DS"),
                    },
                ],
                milestones: &[],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 154_020_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2016),
                    source: source!(wikipedia: "Nintendo_DS"),
                }],
                series: &[],
            },
            Console {
                name: "Nintendo 3DS",
                short_name: "3DS",
                generation: Some(8),
                releases: &[
                    Release {
                        region: Region::JP,
                        date: PartialDate::ymd(2011, 2, 26),
                        source: source!(wikipedia: "Nintendo_3DS"),
                    },
                    Release {
                        region: Region::EU,
                        date: PartialDate::ymd(2011, 3, 25),
                        source: source!(wikipedia: "Nintendo_3DS"),
                    },
                    Release {
                        region: Region::NA,
                        date: PartialDate::ymd(2011, 3, 27),
                        source: source!(wikipedia: "Nintendo_3DS"),
                    },
                ],
                milestones: &[Milestone {
                    kind: MilestoneKind::Discontinued,
                    date: PartialDate::ymd(2020, 9, 16),
                    region: Region::Global,
                    source: source!(wikipedia: "Nintendo_3DS"),
                }],
                measures: &[Measure {
                    kind: MeasureKind::UnitsSold,
                    value: Estimate {
                        point: 75_940_000,
                        low: None,
                        high: None,
                    },
                    region: Region::Global,
                    as_of_year: Some(2022),
                    source: source!(wikipedia: "Nintendo_3DS"),
                }],
                series: &[],
            },
        ],
    },
];
